import { NextIntlClientProvider, hasLocale } from 'next-intl';
import { Raleway } from 'next/font/google'
import { notFound } from 'next/navigation';
import { routing } from '@/i18n/routing';
import { getLocale } from 'next-intl/server';
import "@/project/styles/globals.scss";

const raleway = Raleway({
  weight: ['400', '500', '700'],
  subsets: ['latin', 'cyrillic'],
  style: ['normal', 'italic'],
  display: 'swap',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const locale = await getLocale();

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  };

  return (
    <html lang={locale}>
      <body className={raleway.className}>
        <NextIntlClientProvider>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
};
