import 'swiper/css';
import 'swiper/css/navigation';
import './scss/main.scss';
import './js/faq.js';
import './js/year.js';
import './js/reviews-slider.js';
import './js/services-modal.js';
import './js/header-menu.js';
import './js/symptoms-reveal.js';
